baseURL = 'https://blog.akarinext.org/'
languageCode = 'ja-JP'
title = "あゆき's BLOG"
theme = "hugo-theme-stack-starter"

[params.Sidebar]
    subtitle = "A STUDENT WITH IDEALS AND BELIEFS."
    avatar.src = "img/logo.webp"
