baseURL = 'https://blog.akarinext.org/'
languageCode = 'ja-JP'
title = "あゆき's BLOG"
theme = ["hugo-theme-stack-starter", "hugo-notice"]

DefaultContentLanguage = "ja"

[Params]
    favicon = "img/icon/favicon.ico"

[Params.Sidebar]
    subtitle = "A STUDENT WITH IDEALS AND BELIEFS."
    avatar.src = "img/logo.webp"

[Params.DateFormat]
    published = "1月 02, 2006"
    lastUpdated = "1月 02, 2006 15:04 MST"

[Params.Custom.Authors.yupix]
    name = "yupix"
    icon = "yupix.webp"

[Params.Custom.Authors.aki]
    name = "aki"
    icon = "aki.webp"

