baseURL = 'https://blog.akarinext.org/'
languageCode = 'ja-JP'
title = "あゆき's BLOG"
theme = "hugo-theme-stack-starter"

DefaultContentLanguage = "ja"

[params.Sidebar]
    subtitle = "A STUDENT WITH IDEALS AND BELIEFS."
    avatar.src = "img/logo.webp"

[params.DateFormat]
    published = "1月 02, 2006"
    lastUpdated = "1月 02, 2006 15:04 MST"

[params.Custom.Authors.yupix]
    name = "yupix"
    icon = "yupix.webp"

[params.Custom.Authors.aki]
    name = "aki"
    icon = "aki.webp"
